# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitioned_well', models.BooleanField(default=False)),
                ('asked_why_questions', models.IntegerField(default=0)),
                ('creative_play', models.IntegerField(default=0)),
                ('listened_well', models.IntegerField(default=0)),
                ('not_there', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('modification_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=16)),
                ('condition', models.CharField(max_length=8)),
                ('start_date', models.DateTimeField(verbose_name='study start date')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=32)),
                ('participant_initials', models.CharField(max_length=4)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.LocationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='dailytracker',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.LocationInfo'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.DailyTracker'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Participants'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
