# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('mod_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mod_date', models.DateTimeField(verbose_name='Last Modified Date')),
                ('transitioned_well', models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3')], default=1)),
                ('asked_why_questions', models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3')], default=1)),
                ('creative_play', models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3')], default=1)),
                ('listened_well', models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3')], default=1)),
                ('not_there', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=16)),
                ('condition', models.CharField(choices=[('tl', 'TL'), ('dtn', 'DTN'), ('dtn_plus', 'DTN+')], max_length=8)),
                ('start_date', models.DateField(help_text='mm/dd/yyyy')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_initials', models.CharField(max_length=4, unique=True)),
                ('participant_name', models.CharField(blank=True, max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_location', models.FilePathField(path='/media/sd_card/media')),
                ('image_location', models.FilePathField(blank=True, path='/media/sd_card/images')),
                ('description', models.TextField(blank=True)),
                ('num_plays', models.IntegerField(blank=True, default=0)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Location')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_played', models.FilePathField(blank=True, path='/media/sd_card/media')),
                ('video_recorded', models.FilePathField(blank=True, path='/media/sd_card/images')),
                ('watch_date', models.DateTimeField()),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Location')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Location'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Participant'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Location'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Participant'),
        ),
    ]
